name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: |
          zip -r collection_miner.zip . -x "*.git*" -x ".github/*" -x "*.DS_Store" -x "node_modules/*" -x "*.md" -x ".gitignore"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: collection_miner.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
